import turtle
turtle.Screen().setup(700,500)
turtle.Screen().bgpic("indagate.gif")
turtle.colormode(255)
turtle.bgcolor(254, 245, 231)
turtle.hideturtle()

def rect(color,width,height):
    turtle.begin_fill()
    turtle.fillcolor(color)
    for _ in range(2):
        turtle.forward(width)
        turtle.right(90)
        turtle.forward(height)
        turtle.right(90)
    turtle.end_fill()

def chakram(radius):
    turtle.color(6, 3, 141)
    turtle.setheading(0)
    turtle.penup()
    turtle.left(90)
    turtle.forward(radius/2)
    turtle.pendown()

    for _ in range(24):
       
        
        turtle.forward(radius)
        turtle.backward(radius)
        turtle.right(360/24)
saffron=(255,153,51)
green=(19,136,8)
turtle.penup()
turtle.goto(-650,-375)
turtle.color("black")

turtle.pendown()
turtle.speed(8)
turtle.begin_fill()
turtle.fillcolor(254, 245, 231)
turtle.left(90)
turtle.forward(750)
turtle.right(90)
turtle.forward(1300)
turtle.right(90)
turtle.forward(750)
turtle.right(90)
turtle.forward(1300)
turtle.end_fill()
turtle.penup()
turtle.goto(-625,-350)
turtle.color("black")

turtle.pendown()
turtle.speed(6)
turtle.left(270)
turtle.forward(700)
turtle.right(90)
turtle.forward(1250)
turtle.right(90)
turtle.forward(700)
turtle.right(90)
turtle.forward(1250)
turtle.penup()
turtle.goto(250,100)
turtle.pendown()
turtle.speed(5)
rect(saffron,500,100)
turtle.penup()
turtle.goto(250,0)
turtle.pendown()
rect("white",500,100)
turtle.penup()
turtle.goto(250,-100)
turtle.down()
rect(green,500,100)

turtle.penup()
turtle.goto(-5,0)
turtle.width(2)
turtle.pendown()
turtle.color(6, 3, 141)
turtle.setheading(0)
turtle.speed(3)
turtle.circle(50)
turtle.penup()
turtle.width(2)
turtle.goto(-5,25)
turtle.pendown()
chakram(50)
turtle.color("black")
turtle.speed(5)
for _ in range(3):
    turtle.penup()
    turtle.goto(-605,310)
    turtle.pendown()
    turtle.write("From",font=("Courier New",20,"normal"))
    turtle.penup()
    turtle.goto(-605,270)
    turtle.pendown()
    turtle.write("Aashin Mohammed A Z",font=("Courier New",20,"normal"))
    turtle.penup()
    turtle.goto(-605,240)
    turtle.pendown()
    turtle.write("Trivandrum",font=("Courier New",20,"normal"))


    turtle.penup()
    turtle.goto(465,-250)
    turtle.pendown()
    turtle.write("To",font=("Courier New",20,"normal"))

    turtle.penup()
    turtle.goto(465,-280)
    turtle.pendown()
    turtle.write("TinkerHub",font=("Courier New",20,"normal"))

    turtle.penup()
    turtle.goto(465,-310)
    turtle.pendown()
    turtle.write("CUCEK",font=("Courier New",20,"normal"))

    turtle.penup()
    turtle.goto(-525,-270)
    turtle.pendown()
    turtle.write("Subject:Code-A-Flag,78th Independence Day",font=("Courier New",20,"normal"))


turtle.done()
